name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y build-essential

    - name: Build clean
      run: |
        make clean

    - name: Run clean and process wbcd
      run: |
        ./clean < wbcd.txt > cleaned_wbcd.txt

    - name: Upload cleaned_wbcd.txt
      uses: actions/upload-artifact@v4
      with:
        name: cleaned_wbcd
        path: cleaned_wbcd.txt
